name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build JAR
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-java-app:latest .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-java-app:latest

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
           echo "${{ secrets.GCP_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy on GCP VM
          run: |
            SSH_KEY_PATH=~/.ssh/id_rsa
            ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} "
              docker pull ${{ secrets.DOCKER_USERNAME }}/hello-java-app:latest
              docker stop app || true
              docker rm app || true
              docker run -d --name app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/hello-java-app:latest
            "

          

